catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('mamandyks/', views.MamandykListView.as_view(), name='mamandyks'),
    path('mamandyk/<int:pk>', views.MamandykDetailView.as_view(), name='mamandyk-detail'),
    path('mugalims/', views.MugalimListView.as_view(), name='mugalims'),
    path('mugalim/<int:pk>', views.MugalimDetailView.as_view(), name='mugalim-detail'),
]
urlpatterns += [
    path('mymamandyks/', views.LoanedMamandyksByUserListView.as_view(), name='my-borrowed'),
]
urlpatterns += [
    path('mamandyks/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-mamandyks-librarian'),
]

localibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User

class Kafedra(models.Model):

    name = models.CharField(max_length=200, help_text=" ")
    
    
    def __str__(self):

        return self.name

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Mamandyk(models.Model):

    title = models.CharField(max_length=200)
    mugalim = models.ForeignKey('Mugalim', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text=' ')
    isbn = models.CharField('ISBN',max_length=15, help_text=' ')
    kafedra = models.ManyToManyField(Kafedra, help_text=' ')

    
   
    def display_genre(self):

        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
	
    display_genre.short_description = 'Kafedra'
    
    def __str__(self):

        return self.title
		
    def get_absolute_url(self):

        return reverse('book-detail', args=[str(self.id)])

import uuid

class Kurs(models.Model):

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text=" ")
    book = models.ForeignKey('Mamandyk', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('1', 'bir'),
        ('2', 'eki'),
        ('3', 'ush'),
        ('4', 'tort'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text=' ')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)
        

    def __str__(self):

        return '{0} ({1})'.format(self.id,self.book.title)

class Mugalim(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ["last_name","first_name"]
    
    def get_absolute_url(self):

        return reverse('author-detail', args=[str(self.id)])
    

    def __str__(self):

        return '{0}, {1}'.format(self.last_name,self.first_name)
   

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.
    
class RenewMamandykForm(forms.Form):
    renewal_date = forms.DateField(help_text=" ")

    def clean_renewal_date(self):
        data = self.cleaned_data[' ']
        
        #Check date is not in past. 
        if data < datetime.date.today():
            raise ValidationError(_(' '))

        #Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_(' '))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Mugalim, Mamandyk, Kurs


def num_mamandyks():
    pass
def num_mugalims():
    pass

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_books=Mamandyk.objects.all().count()
    num_instances=Kurs.objects.all().count()
    # Available books (status = 'a')
    num_instances_available=Kurs.objects.filter(status__exact='a').count()
    num_authors=Mugalim.objects.count()  # The 'all()' is implied by default.
    
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_mamandyks':num_mamandyks,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_mugalims':num_mugalims,
            'num_visits':num_visits}, # num_visits appended
    )
from django.views import generic

class MamandykListView(generic.ListView):
    model = Mamandyk
    paginate_by = 2
class MamandykDetailView(generic.DetailView):
    model = Mamandyk
from django.views import generic

class MugalimListView(generic.ListView):
    model = Mugalim
class MugalimDetailView(generic.DetailView):
    model = Mugalim
    model2=Mamandyk
    paginate_by = 2
from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedMamandyksByUserListView(LoginRequiredMixin,generic.ListView):

    model =Kurs
    template_name ='catalog/kurs_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return Kurs.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
from django.contrib.auth.decorators import permission_required

from django.contrib.auth.decorators import permission_required

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

from .forms import RenewMamandykForm


def mamandyk_inst(args):
    pass


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    mamandyk_inst=get_object_or_404(Kurs, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewMamandykForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            mamandyk_inst.due_back = form.cleaned_data['renewal_date']
            mamandyk_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewMamandykForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/mamandyk_renew_librarian.html', {'form': form, 'mamandykinst':mamandyk_inst})

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'mamandyks' %}">All mamandyks</a></li>
          <li><a href="{% url 'mugalims' %}">All mugalims</a></li>
          {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>AUTHOR: {{ author.first_name }}, {{ author.last_name }} </h1>
  </n>{{author.date_of_birth}}
  <div style="margin-left:20px;margin-top:20px">
  <p><strong>Mamandyks:</strong> {{ book.title }}</p>
  <p><strong>last_name:</strong> <a href="">{{ author.last_name }}</a></p>
  <p><strong>first_name:</strong> <a href="">{{ author.first_name }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>date_of_birth:</strong> {{ author.date_of_birth }}</p> 
  <p><strong>date_of_death:</strong> {{ author.date_of_death }}</p>  
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Mugalim List</h1>

    {% if mugalim_list %}
    <ul>

      {% for mugalim in mugalim_list %}
      <li>
        <a href="{{ mugalim.get_absolute_url }}">{{mugalim.first_name}},{{mugalim.last_name}}({{mugalim.date_of_birth}})</a> ({{mugalim.date_of_death}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>   </p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Mugalim:</strong> <a href="{% url 'mugalim-detail' book.mugalim.pk %}">{{ book.mugalim }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Kafedra:</strong> {% for kafedra in mamandyk.kafedra.all %} {{ kafedra }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in mamandyk.kurs_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if mamandyk_list %}
    <ul>

      {% for mamandyk in mamandyk_list %}
      <li>
        <a href="{{ mamandyk.get_absolute_url }}">{{mamandyk.title }}</a> ({{mamandyk.mugalim}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>...  </p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{kurs.mamandyk.title}}</h1>
    <p>Borrower: {{kurs.borrower}}</p>
    <p{% if kurs.is_overdue %} class="text-danger"{% endif %}>Due date: {{kurs.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed mamandyks</h1>

    {% if kurs_list %}
    <ul>

      {% for kurs in kurs_list %}
      <li class="{% if kurs.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' kurs.book.pk %}">{{kurs.mamandyk.title}}</a> ({{ kurs.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>...</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>  KAFEDRA</h1>

<ul>
<li><strong>Mamandyks:</strong> {{ num_mamandyks }}</li>
<li><strong>Copies:</strong> {{ num_instances }}</li>
<li><strong>Copies 3:</strong> {{ num_instances_available }}</li>
<li><strong>Mugalims:</strong> {{ num_mugalims }}</li>
</ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}